FROM nginx:alpine

COPY ./dist/currency-converter /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY src/docker/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
